// demo-vue/app/components/App.vue
<template>
    <Page>
        <ActionBar title="OAuth Demo: NativeScript-Vue"/>
        <StackLayout class="p-20">
            <Button text="Login" @tap="onLoginTap()" class="btn btn-primary btn-active"/>
            <Button text="Logout" @tap="onLogoutTap()" class="btn btn-primary btn-active"/>
        </StackLayout>
    </Page>
</template>

<script>
    var auth_service_1 = require("../auth-service");


  export default {
    data() {
      return {}
    },
    methods: {
        onLoginTap() {
            auth_service_1.tnsOauthLogin("facebook");
        },
        onLogoutTap() {
            auth_service_1.tnsOauthLogout();
        }
    }
  }
</script>

<style scoped>
    ActionBar {
        background-color: #53ba82;
        color: #ffffff;
    }

    .message {
        vertical-align: center;
        text-align: center;
        font-size: 20;
        color: #333333;
    }
</style>

// demo-angular/src/app/app.component.ts
import { Component } from "@angular/core";
import { AuthService } from "./auth.service";
import { ITnsOAuthTokenResult } from "nativescript-oauth2";
import { Page } from "tns-core-modules/ui/page/page";
import { topmost } from "tns-core-modules/ui/frame";

@Component({
    selector: "ns-app",
    moduleId: module.id,
    templateUrl: "./app.component.html"
})
export class AppComponent {
    constructor(private authService: AuthService, private page: Page) { }

    public onTapLogin() {
        const fram = topmost();

        this.authService
            .tnsOauthLogin("facebook")
            .then((result: ITnsOAuthTokenResult) => {
                console.log("back to app component with token" + result.accessToken);
            });
    }

    public onTapLogout() {
        this.authService.tnsOauthLogout();
    }
}

<StackLayout class="p-20">

    <Button text="Login" (tap)="onTapLogin()" class="btn btn-primary btn-active"></Button>
    <Button text="Logout" (tap)="onTapLogout()" class="btn btn-primary btn-active"></Button>

</StackLayout>
